### PR TITLE
correlation annoucement post

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
what do you think?

**Comment by mattansb** [comment]
pretty cool stuff... (:
--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab <http://www.deverplab.com/>
Personal Website <https://sites.google.com/view/mattansb>

**Comment by strengejacke** [comment]
Yeah looks great! to add some spice, you could include the plot example from the readme

**Comment by DominiqueMakowski** [comment]
the one using `see`?

**Comment by strengejacke** [comment]
Yes, I think that's a nice plot! :-) Or doesn't it fit into your structure of the post? If this plot comes somehow surprisingly and is not related to what you have written before, you can skip the plot.

**Pull request merged**
