### PR TITLE
anniversary post

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
It's been one year, and I thought it would be good idea to have an anniversary post. Let me know what you think, and if you want to change stuff (for instance related to your mention, if you want to advertise something in particular, change your nickname or so :)

### CODE REVIEW

**Comment by strengejacke** [comment]
yeah, cool posting! I like it! :-)

**Comment by DominiqueMakowski** [comment]
*ping* @pdwaggoner @humanfactors @IndrajeetPatil @lindeloev @jacob-long

**Comment by pdwaggoner** [comment]
@DominiqueMakowski great idea! I made a few changes in the PR I just opened. Thanks again for driving the ship here. Exciting (and productive) times!

**Comment by DominiqueMakowski** [comment]
Mmh for some reason now when I run `blogdown::serve_site()` the theme is not showing properly (it shows the raw html page). Is it related to my update of blogdown? Could someone try putting himself on this branch (easystats_oneyear), and run `blogdown::serve_site()` and see if it shows a proper website (with the purple background)? Thanks

**Comment by mattansb** [comment]
> Could someone try putting himself on this branch (easystats_oneyear), and run blogdown::serve_site() and see if it shows a proper website (with the purple background)? 

Works for me..

**Comment by DominiqueMakowski** [comment]
Shouldn't have updated blogdown 😠 okay, I'll try later on my other computer but otherwise you'll have to build the website 😁

**Comment by DominiqueMakowski** [comment]
Let's merge this :)

**Pull request merged**
