### PR TITLE
parameters V2

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Review by strengejacke — COMMENTED** [review]
looks good! When we find the time, we can add blog post that address specific problems, but as initial post I like the overview, because we have added quite a lot different stuff to the current update...

**Comment by DominiqueMakowski** [comment]
✔️ 

Scheduled for release on Monday?

**Comment by DominiqueMakowski** [comment]
🚀

**Comment by strengejacke** [comment]
Dann, i Just copied the code chunk... It should be echo=TRUE, not FALSE, else you can't see the code in the glmmTMB example...

**Comment by strengejacke** [comment]
Couldn't test it because I couldn't pull the branch...

**Comment by DominiqueMakowski** [comment]
I think it's okay like this tho!

**Comment by strengejacke** [comment]
But you don't get a feeling about what is displayed?

**Comment by strengejacke** [comment]
Can we just update one post, or do we have to update the complete blog again (replacing `blog/blog` etc.?)

**Comment by strengejacke** [comment]
probably it's too much effort, and indeed it's ok to leave it as it is now.

**Comment by DominiqueMakowski** [comment]
You can change it in the master branch without rebuilding the site, so we will have it fixed for the next update, but yeah the blogpost is already on Rbloggers so... (and i won't update it there anyway) :)

**Pull request merged**
