### PR TITLE
add post

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
Not sure if this will work, this GitHub blog is a mess... ;-)

**Comment by DominiqueMakowski** [comment]
Good idea!!

**Comment by DominiqueMakowski** [comment]
> Not sure if this will work, this GitHub blog is a mess... ;-)

it sorta works so I guess it's something 🙆‍♂

**Comment by strengejacke** [comment]
feel free to merge, or to modify/add/... :-)
I'm away for the next 3 hours, but I thought it's nice to have this "teaser" on r-bloggers, which might catch some attention...

**Comment by DominiqueMakowski** [comment]
Definitely! Is it okay if I merge tomorrow morning (Singapore) [I feel like it stays up a lot longer because it seems like the rbloggers website is on the US timezone, so it stays "recent" longer]?

**Pull request merged**
