### PR TITLE
Insight presentation

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
@strengejacke  I was thinking that as insight is on CRAN and all, a small post announcing it could be great. We could then write more specific posts about specific features and their complexities (kinds of parameters, kinds of variance etc.).

I quickly made a draft of a possible announcement post, what do you think?

### CODE REVIEW

**Comment by strengejacke** [comment]
Yeah, looks good! Let's publish this to raise some attention, and then indeed we can write more blogposts on details.

**Comment by DominiqueMakowski** [comment]
I'll let you PR the final `blogdown::serve_site()` and merge this whenever you think it's ok (the date will need to be changed appropriately ;)

**Comment by strengejacke** [comment]
So, what's the current way to publish a page? Simply push the .rmd to `contents`?

**Comment by strengejacke** [comment]
Feel free to merge the PR, I'm away from Thursday to Sunday, so you may release this post.

**Comment by DominiqueMakowski** [comment]
Add a `.Rmd` to contents, then run `blogdown::serve_site()` so it builds the corresponding html and shows you the site locally, and if everything is ok, you just push everything

**Comment by DominiqueMakowski** [comment]
Merged, we can delete the branch (as here I think it's easier (?) to have one branch per post)

**Pull request merged**
