### PR TITLE
new emmeans + bayestesR post

### PR DESCRIPTION
**Pull request by mattansb**
I've tried to keep this practical-oriented, so it is *very* light on theory (This is also a rough draft right now..).

Let me know what is missing / should be polished, and feel free to add any opening or closing statements / remarks (like those in previous easystats posts).

### CODE REVIEW

**Comment by strengejacke** [comment]
I made some minor revisions. One sentence:

> Using the fantastic **emmeans** package, we can explore and extract estimates from our fitted model.

Do we extract _estimates_ in a classical sense? Wouldn't it be more clear to say "marginal estimates", or "marginal effects" or so?

**Comment by strengejacke** [comment]
Just curious, you called the priors "non-informed", though you were giving location/scale. Is there somewhere a definition when a prior is "flat", "weakly informative", "informative", "uninformed"? I thought the priors you are using were "weakly informative".

**Comment by DominiqueMakowski** [comment]
To my knowledge (non-uniform) priors located at 0 with a not-too-narrow scale are labelled as "weakly informative" and flat (uniform) priors as "non-informative"

**Comment by DominiqueMakowski** [comment]
PS: for the release plan, my suggestion is to 1) wait for confirmation that the blog is back on r-bloggers, 2) release a small "bayestestR v2" post simply advertising the new version and redirecting to the website and 3) release this post showcasing a more complete use of bayestestR

**Comment by mattansb** [comment]
[Rouder et al. (2012)](http://pcl.missouri.edu/sites/default/files/Rouder.JMP_.2012.pdf) seem to equate "weakly informative" with "non-informative", but I'll change this for consistency with [`rstanarm` terminology](http://mc-stan.org/rstanarm/reference/priors.html).

> PS: for the release plan...

Sounds good!

I can't seem to get `blogdown` to work on my end - is it okay if I leave the building etc. up to you?

**Comment by DominiqueMakowski** [comment]
sure :)

**Comment by mattansb** [comment]
Okay, bayestestR is on CRAN! And the blog is back on r bloggers! Let's do this! (Can you tell I'm excited?)

**Comment by mattansb** [comment]
I light of the [new `emmeans` integration](https://github.com/easystats/bayestestR/issues/159), perhaps this post should be scrapped for now? Maybe if `bayestestR` has a minor 0.2.1 release I can update this post and publish it then?
Or we can publish this an intended, and in the future publish a "update - now it's even easier!" post?

@DominiqueMakowski @strengejacke thoughts?

**Comment by mattansb** [comment]
Alternatively, I can update this post to actually demo the new `emmeans` methods, and we can publish it after the `emmeans` PR is completed (noting in the post that this update is available on the GitHub version, and will "soon" be available on CRAN release).

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke I'm tending towards my last suggestion. What do you think?

**Comment by strengejacke** [comment]
I'm open to every suggestions... I just recalled a deadline you mentioned? If this is no longer important for you, go ahead!

**Comment by DominiqueMakowski** [comment]
Yup, I am okay with all alternatives as it mostly depends on your timeline :)

**Comment by mattansb** [comment]
My timeline has changes slightly 😅
I've updated the post - it is ready to build and go up when the PR is completed.

Should I add some note or footnote somewhere that support for emmeans is available on github and in will also on CRAN?

**Comment by mattansb** [comment]
Seems like I can keep my original timeline - this post is ready to go up 🎉

**Comment by DominiqueMakowski** [comment]
Tomorrow then?

**Comment by mattansb** [comment]
Yes, excellent!

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
We must decide on a time zone when we speak of "tomorrow" or "today". :-D

**Comment by DominiqueMakowski** [comment]
In my absolutely unbiased opinion, I would say the time zone of the majority of easystats members... How surprising that it is mine! 😄 

I think Europe's time zone makes sense for everybody as it is "in the middle" (apologies for my eurocentrism :p). Midday in the easystats timezone (henceforth referred to as **the easytime**) is in my afternoon/evening and in the US people's morning

**Comment by strengejacke** [comment]
We could use UTC, which indeed seems to be somewhat Europe-centered ;-)

**Comment by mattansb** [comment]
So in easytime™, when @DominiqueMakowski said "tomorrow", that was referring to Thursday, yes?

**Comment by DominiqueMakowski** [comment]
Correct, how does that sound?

**Comment by mattansb** [comment]
Fantastic :)

**Comment by strengejacke** [comment]
>  in easytime™

We should file a PR in the _lubridate_ package...

**Comment by DominiqueMakowski** [comment]
In fact, I don't even have to merge it... I built the site, so feel free to merge whenever you want :)

**Comment by DominiqueMakowski** [comment]
I think you could definitely link to this blogpost from the BF vignette on bayesfactor. You know in a  paragraph like "More examples of usage" or something like that.

As a matter of fact, if we have more of such feature-specific posts, we might eventually want to either link them from the last tutorial vignette (become a Bayesian master), or create a separate vignette "More examples and resources" to link to these posts.

**Comment by mattansb** [comment]
The post is up + tweeted (the most important part of any publication!).

**Comment by MPLisi** [comment]
It is possible to compute ESS and R^ for each emmean comparison?

**Comment by mattansb** [comment]
@matthewlee37 `emmeans` doesn't save the chains separately, so you can't find rhat.
But in theory it should be possible to manually compute ESS across all chains.

But I think (?) looking at these of the parameter (and note the expected means / contrasts) would be more informative anyway..

**Pull request merged**
