### PR TITLE
bayestestR_presentation

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@strengejacke what do you think? It's *very* short, but it's just an announcement 😅

**Comment by DominiqueMakowski** [comment]
@pdwaggoner Do not hesitate to share opinions 😉

**Comment by pdwaggoner** [comment]
@DominiqueMakowski - I really like the idea of a few blog posts detailing the package functionality after this initial "hey bayestestR is now live!" post. A couple quick thoughts:

1. _Small note_: On line 20 of the `update` commit you just made to `bayestestR_presentation`, the word "Welcome" is misspelled. 

2. Though I know you were thinking subsequent posts detailing functionality, which as I said above is a great idea to bring folks into the package a bit more incrementally, I think a quick tutorial showing something eye-grabbing/fancy from the package in this initial post would be a valuable thing to pull folks in at the outset. You wouldn't even necessarily have to show the code snippet, but you could simply say something like: look what the package can do... [insert cool, intuitive plot/table here]. That was my only thought when reading, as its clear its a great package that fills a gap, but a quick high-level demo would've convinced me to go download the package. Just a thought.  Great work though - I really like it!

**Comment by DominiqueMakowski** [comment]
Corrected stuff, added equivalence test example. If you guys green light this we can release it.

**Comment by pdwaggoner** [comment]
Love it!

**Comment by DominiqueMakowski** [comment]
@strengejacke Are you ok for releasing this tomorrow?

**Comment by strengejacke** [comment]
Looks good! I have added a plot()-example, to have an "eyecatcher" in this blog-post, are you ok with this?

**Comment by DominiqueMakowski** [comment]
I'll merge this tomorrow ☺️

**Pull request merged**
