### PR TITLE
Blog post about new features in parameters 0.11.0

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
@DominiqueMakowski I will never remember which steps to do before publishing a post, I hope this work - could you merge? It's a copy of an existing vignette, but I guess this blog post will get more attention, so this redundancy is probably not bad...

And, I got a warning when rendering the blog post:

```r
> blogdown::build_site()
Building sites â€¦ WARN 2021/01/19 00:38:24 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2021/01/19 00:38:24 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
```

**Comment by DominiqueMakowski** [comment]
> And, I got a warning when rendering the blog post:

I got it too, and it seems like the only instance of this is in the theme: https://github.com/easystats/blog/blob/901f8e25398b3bfc8cb18939e9b2433d56dae29c/themes/hyde-hyde/layouts/partials/header/feeds.html

so I think in the future we can just update the theme to a newest version

**Comment by DominiqueMakowski** [comment]
merging 🤞

**Comment by DominiqueMakowski** [comment]
I changed the date but it didn't (yet?) appear on rbloggers 😕

**Comment by strengejacke** [comment]
Yeah, it usually takes up to one day, so if it worked, we should probably see it by tomorrow

**Pull request merged**
